ALTER TABLE "Attachments" ADD COLUMN IF NOT EXISTS "isEncrypted" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Attachments" ADD COLUMN IF NOT EXISTS "encryptionVersion" TEXT;
ALTER TABLE "DocumentChunks" ADD COLUMN IF NOT EXISTS "isEncrypted" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "DocumentChunks" ADD COLUMN IF NOT EXISTS "encryptionVersion" TEXT;
ALTER TABLE "UserSession" ADD COLUMN IF NOT EXISTS "ipHash" TEXT;
ALTER TABLE "LoginEvent" ADD COLUMN IF NOT EXISTS "ipHash" TEXT;
UPDATE "Attachments" SET "isEncrypted" = false WHERE "isEncrypted" IS NULL;
UPDATE "DocumentChunks" SET "isEncrypted" = false WHERE "isEncrypted" IS NULL;
ALTER TABLE "Attachments" ALTER COLUMN "isEncrypted" SET DEFAULT false;
ALTER TABLE "Attachments" ALTER COLUMN "isEncrypted" SET NOT NULL;
ALTER TABLE "DocumentChunks" ALTER COLUMN "isEncrypted" SET DEFAULT false;
ALTER TABLE "DocumentChunks" ALTER COLUMN "isEncrypted" SET NOT NULL;
CREATE INDEX IF NOT EXISTS "UserSession_ipHash_idx" ON "UserSession"("ipHash");
CREATE INDEX IF NOT EXISTS "LoginEvent_ipHash_timestamp_idx" ON "LoginEvent"("ipHash", "timestamp");
